### PR TITLE
Continuous Integration

### PR DESCRIPTION
**Pull request by Beakerboy**
This patch build the project on Travis-CI and adds a build status badge to the project. 

Before merging (squash and merge), log into Travis-cI.org and allow it to hook into the repository. When this patch is merged, it will trigger the build and the badge will appear.

I will submit other CI improvements as separate patches.

### CODE REVIEW

**Comment by Beakerboy** [comment]
This patch will build the project and run unit tests using Travis-CI

**Comment by NaturalDocs** [comment]
I want to wait a bit until I can remove the need for the xcopy hack, and I have some time to learn more about Travis-CI.

**Comment by Beakerboy** [comment]
If you are going to choose one CI service, Appveyor is probably the one you should look at first. It's Windows based first, but has Ubuntu as well. The Travis-Ci script may be able to be ported to the Ubuntu environment on Appveyor. If you are unfamiliar with them, and want to see how they work, I'd suggest making a new Github account, forking the NaturalDocs repository, linking Travis and/or Appveyor to this new account and applying this patch. Feel free to ask questions. I like NaturalDocs, and want to make it easier for you to review and test patches so new features can be rolled out. CI philosophy is the current "best practice" in this regard.

**Comment by Beakerboy** [comment]
To see the Appveyor results, see https://ci.appveyor.com/project/Beakerboy/naturaldocs/builds/22640055/job/fiaj91wkbphxge49

For Travis, See https://travis-ci.org/Beakerboy/NaturalDocs/builds/498399380

**Comment by Beakerboy** [comment]
One last comment. "Removing the xcopy hack" is the perfect opportunity to test CI. With the current Travis and Appveyor configurations, we know NaturalDocs builds successfully in both Linux and Windows. You can make a change to the project file, push it to a new branch on Github, and the CI service will very quickly let you know if your changes broke the build or not.  If they are successful, you can make a pull request between master and the new branch and merge in the changes without having to worry.

**Pull request closed without merging**
